name: CD

on:
  push:
    tags: v*

jobs:
  
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo "${{ github.ref }}" | sed -e "s/^.*\///")
    - name: Deploy
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build . -f deploy.Dockerfile -t skeggib/steroids:${{ steps.get_version.outputs.VERSION }}
        docker push skeggib/steroids:${{ steps.get_version.outputs.VERSION }}
        docker build . -f deploy.Dockerfile -t skeggib/steroids:latest
        docker push skeggib/steroids:latest
