name: CI

on: [push]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build -f ci-build.Dockerfile .
  
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Unit tests
      run: docker build -f ci-test.Dockerfile .
