name: CI

on:
  push:
    branches:
    - master
    - "feature/**"
    - "bugfix/**"
    tags-ignore: v*

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build -f ci-build.Dockerfile .
  
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Unit tests
      run: docker build -f ci-unit-tests.Dockerfile .
  
  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build app
      run: docker build . -f ci-build.Dockerfile -t ci-build
    - name: Create integration tests image
      run: docker build . -f ci-integration-tests.Dockerfile -t ci-integration-tests
    - name: Run integration tests
      run: docker run ci-integration-tests
